### ISSUE TITLE
Editable Scheduled Monthly Payment

### ISSUE THREAD

**Issue by venkat1806** [javadurai/loanease#2]
This calculator is simple and flexible to use.

One suggestion, Could you make the Scheduled Monthly Payment editable. 

For eg my actual EMI is Rs.13455 but I have scheduled my monthly payment to Rs.25000. I understand we can add the difference as monthly part payment but its not a constant value every month. It differs wrt the EMI.

**Comment by javadurai** [comment]
Hi @venkat1806,

We had this fixed, now you can have the Part Payment for each installment or quarter

![image](https://github.com/javadurai/loanease/assets/45031320/0bebf83e-b318-40d2-ad6a-1b606e95313e)

Can you review and let us know it looks good for you.

You can access the site at https://javadurai.github.io/loanease/
